### ISSUE TITLE
Shooting While Moving

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/Final_Bot_2024#3]
lord help you if you decide to take this task

**Comment by ChaoticChaosTheGreat** [comment]
I got you, I have some funny things to try.

**Comment by ChaoticChaosTheGreat** [comment]
So my funny idea that is probably the easiest to implement, is you get robot velocity and then offeset the distance it is to the speaker based on that. You could also just compare like the last two states of the robot to see what direction its been going. Prob takes a lot of tuning so maybe not for EBR.
