### ISSUE TITLE
Auto: Point to Speaker

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/Final_Bot_2024#37]
Devise an algorithm that will always point to the speaker tag. 

A suggestion is to find the current angle to the speaker pose (swerveDrive.getPose() & kBlueSpeakerPose) and then point the robot at that specific angle. 

You may need to do some transformations to that angle for it to work.

**Comment by realjoshuau** [comment]
@3LucasZ were you able to test this at bell td

**Comment by ThatXliner** [comment]
wouldn't this just be like running the auto-aim periodically? we decided not to do that right

**Comment by realjoshuau** [comment]
finished in RedoConstants
