### ISSUE TITLE
Implement gear ratio(s) for position-based subsystems

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/Final_Bot_2024#45]
- [x] Climb
- [x] IntakePivot
- [x] ShooterPivot

Create a constant called k[Subsystem]Gearing.
Multiply the set position commands with the gearing, and multiply by (1/gearing) when you're returning values to the dashboard/print statements.

**Comment by ThatXliner** [comment]
Note to self: if I want my code to be merged for the season, don’t over-engineer it

**Comment by ChaoticChaosTheGreat** [comment]
done

**Comment by ThatXliner** [comment]
Dang, fastest gun in the west
