### ISSUE TITLE
Auto Align Subwoofer corners/sides

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/Final_Bot_2024#6]
Write code that will auto align to the sides and corners of the subwoofer. (The purple sides)
<img width="131" alt="SCR-20240304-enq" src="https://github.com/Team3256/FRC_Programming_2024/assets/102478723/695c92e1-8f88-43bf-95a2-e6e312362843">

**Comment by ThatXliner** [comment]
Using localization?

**Comment by realjoshuau** [comment]
No
<img width="253" alt="SCR-20240322-flg" src="https://github.com/Team3256/Final_Bot_2024/assets/102478723/84362564-5fd3-480d-9f91-0320b4bac3a7">

**Comment by ChaoticChaosTheGreat** [comment]
we use localization again soooooooooooooooo uh just give pose

**Comment by ChaoticChaosTheGreat** [comment]
done check pr
